version: '3.8'

# 默认启动内存存储模式
services:
  # 默认服务 (内存存储)
  app:
    build: .
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - USE_DATABASE=false
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    restart: unless-stopped
    profiles:
      - memory-only
    deploy:
      resources:
        limits:
          memory: 16G
        reservations:
          memory: 2G
    
  # 带数据库的应用服务
  mysql-binlog-analyzer-db:
    build: .
    ports:
      - "5000:3000"
    environment:
      - NODE_ENV=production
      - USE_DATABASE=true
      - DB_HOST=mysql
      - DB_USER=binlog_user
      - DB_PASSWORD=binlog_pass
      - DB_NAME=binlog_analyzer
    volumes:
      - ./uploads:/app/uploads
      - ./logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
    restart: unless-stopped
    profiles:
      - with-database
    deploy:
      resources:
        limits:
          memory: 8G
        reservations:
          memory: 1G
    
  # MySQL数据库服务
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: binlog123
      MYSQL_DATABASE: binlog_analyzer
      MYSQL_USER: binlog_user
      MYSQL_PASSWORD: binlog_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    restart: unless-stopped
    profiles:
      - with-database
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "binlog_user", "-pbinlog_pass"]
      timeout: 20s
      retries: 10
      interval: 10s
      start_period: 40s

volumes:
  mysql_data: